version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 172.20.80.1
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{ print $$2 }'"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "WeatherData:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  #codingexercise:
  #  image: codingexercise
  #  build:
  #    context: .
  #    dockerfile: ./Dockerfile
  #  ports:
  #    - 5000:5000
  #  depends_on:
  #    - kafka

